# Generated by Django 5.2.9 on 2025-12-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('POWER', 'Power User'), ('USER', 'User'), ('VIEWER', 'Viewer')], default='USER', max_length=10),
        ),
    ]
