# Generated by Django 5.2.9 on 2025-12-08 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_issuance_rejection_comment_issuance_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shade', models.CharField(max_length=100)),
                ('tkt', models.CharField(max_length=100)),
                ('bin_no', models.CharField(max_length=100)),
                ('column_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('EXPORT', 'Export')], max_length=10)),
                ('brand', models.CharField(max_length=100)),
                ('qty_change', models.IntegerField()),
                ('old_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('action', models.CharField(choices=[('CREATE', 'Created new stock'), ('UPDATE', 'Updated existing stock'), ('REVERT', 'Reverted registration')], max_length=10)),
                ('is_reverted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reverted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.registrationlog')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_logs', to='inventory.thread')),
            ],
        ),
    ]
